name: Build And Release GooseMod Dev

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'building/**'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js v15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install NPM dependencies
        run: npm ci

      - name: Build GooseMod
        run: npm run build

      - name: Create dev release
        run: |
          gh release delete ${{ env.VERSION }} -y
          gh release create ${{ env.VERSION }} -p -t "${{ env.NAME }}" ${{ env.FILES }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          VERSION: 'dev'
          NAME: 'GooseMod Dev'
          FILES: dist/index.js
